create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  is_target_person boolean not null default true,
  answers jsonb not null default '{}'::jsonb,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- No public policies are intentionally created.
-- The server uses the Supabase service-role key, kept only in Netlify environment variables.
